title: "luciacacti homepage"
description: "this is a school project i have no idea what i am doing at all. my name is luciacacti and i go to a school and i have never been employed before but i draw online for money its pretty sick. you should pay me 250 dollers for a cool picture i dont have a portfolio so just trust me on this one"
theme: jekyll-theme-minimal                
